filebeat.inputs:
  - type: log
    paths:
      - /project/log/app.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.ilm.enabled: false
